package com.geek.guiyu.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Comments implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.coid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.cid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.deleted
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.author
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.authorid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.ownerid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Integer ownerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.email
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.ip
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.agent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.status
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.parent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.text
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.coid
     *
     * @return the value of comments.coid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.coid
     *
     * @param coid the value for comments.coid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.cid
     *
     * @return the value of comments.cid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.cid
     *
     * @param cid the value for comments.cid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.deleted
     *
     * @return the value of comments.deleted
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.deleted
     *
     * @param deleted the value for comments.deleted
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.author
     *
     * @return the value of comments.author
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.author
     *
     * @param author the value for comments.author
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.authorid
     *
     * @return the value of comments.authorid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.authorid
     *
     * @param authorid the value for comments.authorid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.ownerid
     *
     * @return the value of comments.ownerid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.ownerid
     *
     * @param ownerid the value for comments.ownerid
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.email
     *
     * @return the value of comments.email
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.email
     *
     * @param email the value for comments.email
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.ip
     *
     * @return the value of comments.ip
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.ip
     *
     * @param ip the value for comments.ip
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.agent
     *
     * @return the value of comments.agent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.agent
     *
     * @param agent the value for comments.agent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.status
     *
     * @return the value of comments.status
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.status
     *
     * @param status the value for comments.status
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.parent
     *
     * @return the value of comments.parent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.parent
     *
     * @param parent the value for comments.parent
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.text
     *
     * @return the value of comments.text
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.text
     *
     * @param text the value for comments.text
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Tue Mar 31 20:43:01 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coid=").append(coid);
        sb.append(", cid=").append(cid);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", author=").append(author);
        sb.append(", authorid=").append(authorid);
        sb.append(", ownerid=").append(ownerid);
        sb.append(", email=").append(email);
        sb.append(", ip=").append(ip);
        sb.append(", agent=").append(agent);
        sb.append(", status=").append(status);
        sb.append(", parent=").append(parent);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}