package com.geek.guiyu.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Community implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.id
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.create_time
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.update_time
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.deleted
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.author
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.author_id
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.ip
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.agent
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private String agent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.parent_id
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.replyid
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer replyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.view_num
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer viewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.comment_num
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer commentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.thumb_num
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private Integer thumbNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.text
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.id
     *
     * @return the value of community.id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.id
     *
     * @param id the value for community.id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.create_time
     *
     * @return the value of community.create_time
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.create_time
     *
     * @param createTime the value for community.create_time
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.update_time
     *
     * @return the value of community.update_time
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.update_time
     *
     * @param updateTime the value for community.update_time
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.deleted
     *
     * @return the value of community.deleted
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.deleted
     *
     * @param deleted the value for community.deleted
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.author
     *
     * @return the value of community.author
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.author
     *
     * @param author the value for community.author
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.author_id
     *
     * @return the value of community.author_id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.author_id
     *
     * @param authorId the value for community.author_id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.ip
     *
     * @return the value of community.ip
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.ip
     *
     * @param ip the value for community.ip
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.agent
     *
     * @return the value of community.agent
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.agent
     *
     * @param agent the value for community.agent
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.parent_id
     *
     * @return the value of community.parent_id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.parent_id
     *
     * @param parentId the value for community.parent_id
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.replyid
     *
     * @return the value of community.replyid
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.replyid
     *
     * @param replyid the value for community.replyid
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.view_num
     *
     * @return the value of community.view_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.view_num
     *
     * @param viewNum the value for community.view_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.comment_num
     *
     * @return the value of community.comment_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.comment_num
     *
     * @param commentNum the value for community.comment_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.thumb_num
     *
     * @return the value of community.thumb_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public Integer getThumbNum() {
        return thumbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.thumb_num
     *
     * @param thumbNum the value for community.thumb_num
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setThumbNum(Integer thumbNum) {
        this.thumbNum = thumbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.text
     *
     * @return the value of community.text
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.text
     *
     * @param text the value for community.text
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Fri Apr 03 20:29:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", author=").append(author);
        sb.append(", authorId=").append(authorId);
        sb.append(", ip=").append(ip);
        sb.append(", agent=").append(agent);
        sb.append(", parentId=").append(parentId);
        sb.append(", replyid=").append(replyid);
        sb.append(", viewNum=").append(viewNum);
        sb.append(", commentNum=").append(commentNum);
        sb.append(", thumbNum=").append(thumbNum);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}