package com.geek.guiyu.domain.model;

import java.io.Serializable;
import java.util.Comparator;
import java.util.Date;

public class Contents implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.cid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.title
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.create_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.update_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.uid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.type
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.status
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.password
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.comments_num
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer commentsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.parent
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.love_count
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer loveCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.views
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.allow_comments
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Byte allowComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.is_hot
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Byte isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.order
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.text
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.cid
     *
     * @return the value of contents.cid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.cid
     *
     * @param cid the value for contents.cid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.title
     *
     * @return the value of contents.title
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.title
     *
     * @param title the value for contents.title
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.create_time
     *
     * @return the value of contents.create_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.create_time
     *
     * @param createTime the value for contents.create_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.update_time
     *
     * @return the value of contents.update_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.update_time
     *
     * @param updateTime the value for contents.update_time
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.uid
     *
     * @return the value of contents.uid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.uid
     *
     * @param uid the value for contents.uid
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.type
     *
     * @return the value of contents.type
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.type
     *
     * @param type the value for contents.type
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.status
     *
     * @return the value of contents.status
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.status
     *
     * @param status the value for contents.status
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.password
     *
     * @return the value of contents.password
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.password
     *
     * @param password the value for contents.password
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.comments_num
     *
     * @return the value of contents.comments_num
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getCommentsNum() {
        return commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.comments_num
     *
     * @param commentsNum the value for contents.comments_num
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setCommentsNum(Integer commentsNum) {
        this.commentsNum = commentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.parent
     *
     * @return the value of contents.parent
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.parent
     *
     * @param parent the value for contents.parent
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.love_count
     *
     * @return the value of contents.love_count
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getLoveCount() {
        return loveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.love_count
     *
     * @param loveCount the value for contents.love_count
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setLoveCount(Integer loveCount) {
        this.loveCount = loveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.views
     *
     * @return the value of contents.views
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.views
     *
     * @param views the value for contents.views
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.allow_comments
     *
     * @return the value of contents.allow_comments
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Byte getAllowComments() {
        return allowComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.allow_comments
     *
     * @param allowComments the value for contents.allow_comments
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setAllowComments(Byte allowComments) {
        this.allowComments = allowComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.is_hot
     *
     * @return the value of contents.is_hot
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.is_hot
     *
     * @param isHot the value for contents.is_hot
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.order
     *
     * @return the value of contents.order
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.order
     *
     * @param order the value for contents.order
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.text
     *
     * @return the value of contents.text
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.text
     *
     * @param text the value for contents.text
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", uid=").append(uid);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", password=").append(password);
        sb.append(", commentsNum=").append(commentsNum);
        sb.append(", parent=").append(parent);
        sb.append(", loveCount=").append(loveCount);
        sb.append(", views=").append(views);
        sb.append(", allowComments=").append(allowComments);
        sb.append(", isHot=").append(isHot);
        sb.append(", order=").append(order);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


}