package com.geek.guiyu.domain.model;

import java.io.Serializable;
import java.util.Date;

public class LoveContents implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.id
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.create_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.update_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.cid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.uid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column love_contents.deleted
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.id
     *
     * @return the value of love_contents.id
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.id
     *
     * @param id the value for love_contents.id
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.create_time
     *
     * @return the value of love_contents.create_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.create_time
     *
     * @param createTime the value for love_contents.create_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.update_time
     *
     * @return the value of love_contents.update_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.update_time
     *
     * @param updateTime the value for love_contents.update_time
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.cid
     *
     * @return the value of love_contents.cid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.cid
     *
     * @param cid the value for love_contents.cid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.uid
     *
     * @return the value of love_contents.uid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.uid
     *
     * @param uid the value for love_contents.uid
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_contents.deleted
     *
     * @return the value of love_contents.deleted
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_contents.deleted
     *
     * @param deleted the value for love_contents.deleted
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", cid=").append(cid);
        sb.append(", uid=").append(uid);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}