package com.geek.guiyu.domain.model;

import java.io.Serializable;
import java.util.Date;

public class UserFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.create_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.update_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.deleted
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_url
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.topic
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.describes
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private String describes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.id
     *
     * @return the value of user_file.id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.id
     *
     * @param id the value for user_file.id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.create_time
     *
     * @return the value of user_file.create_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.create_time
     *
     * @param createTime the value for user_file.create_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.update_time
     *
     * @return the value of user_file.update_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.update_time
     *
     * @param updateTime the value for user_file.update_time
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.deleted
     *
     * @return the value of user_file.deleted
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.deleted
     *
     * @param deleted the value for user_file.deleted
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_url
     *
     * @return the value of user_file.file_url
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_url
     *
     * @param fileUrl the value for user_file.file_url
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.topic
     *
     * @return the value of user_file.topic
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.topic
     *
     * @param topic the value for user_file.topic
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.describes
     *
     * @return the value of user_file.describes
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public String getdescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.describes
     *
     * @param describes the value for user_file.describes
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setdescribes(String describes) {
        this.describes = describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_id
     *
     * @return the value of user_file.user_id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_id
     *
     * @param userId the value for user_file.user_id
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbggenerated Thu Mar 19 00:04:29 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", topic=").append(topic);
        sb.append(", describes=").append(describes);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}