package com.geek.guiyu.infrastructure.dao;

import com.geek.guiyu.domain.model.Contents;
import com.geek.guiyu.domain.model.ContentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int countByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int deleteByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int insert(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int insertSelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    List<Contents> selectByExampleWithBLOBs(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    List<Contents> selectByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    Contents selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByExample(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByPrimaryKeySelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbggenerated Wed Apr 01 22:17:24 CST 2020
     */
    int updateByPrimaryKey(Contents record);
}