package com.geek.guiyu.infrastructure.dao;

import com.geek.guiyu.domain.model.LoveContents;
import com.geek.guiyu.domain.model.LoveContentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoveContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int countByExample(LoveContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int deleteByExample(LoveContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int insert(LoveContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int insertSelective(LoveContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    List<LoveContents> selectByExample(LoveContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    LoveContents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") LoveContents record, @Param("example") LoveContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int updateByExample(@Param("record") LoveContents record, @Param("example") LoveContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int updateByPrimaryKeySelective(LoveContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_contents
     *
     * @mbggenerated Thu Apr 02 17:50:39 CST 2020
     */
    int updateByPrimaryKey(LoveContents record);
}