package com.geek.guiyu.infrastructure.dao;

import com.geek.guiyu.domain.model.UserFollow;
import com.geek.guiyu.domain.model.UserFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int countByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int deleteByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    List<UserFollow> selectByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    UserFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int updateByExample(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Tue Mar 17 23:14:16 CST 2020
     */
    int updateByPrimaryKey(UserFollow record);
}